apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-ui-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-ui-service
  template:
    metadata:
      labels:
        app: customer-ui-service
    spec:
      containers:
      - name: customer-ui
        image: maxenceabrt/customer-ui-service:latest
        ports:
        - containerPort: 8080