apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-ui-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-ui-service
  template:
    metadata:
      labels:
        app: customer-ui-service
    spec:
      containers:
      - name: customer-ui-service
        image: maxenceabrt/customer-ui-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: customer-ui-service
spec:
  selector:
    app: customer-ui-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 8080
  type: LoadBalancer