apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-ui-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-ui-service
  template:
    metadata:
      labels:
        app: customer-ui-service
    spec:
      automountServiceAccountToken: false
      containers:
      - name: customer-ui
        image: maxenceabrt/customer-ui-service:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "512Mi"
            cpu: "1"
            ephemeral-storage: "2Gi"