apiVersion: v1
kind: Service
metadata:
  name: customer-ui-service
spec:
  type: LoadBalancer
  selector:
    app: customer-ui-service
  ports:
    - protocol: TCP
      port: 3000         
      targetPort: 8080